language: node_js
node_js:
- "7"

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.tar.gz -O ../hugo.tar.gz
- tar -C .. -zxf ../hugo.tar.gz hugo

script:
- ../hugo

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: m5qt7NLfA+uEEsbnEi9B/gMhznhf3sRJLr17Nm0rYDZQImvhl0Jw7w5pyo2xhwT7QZDlTfyZw8skkkm4nwdLRA6hFFViLajJAcyKUNUJayuSdFkQZH80rfDboPS7DGeHXa8Pb0O1a15hX7zKYIwcY3kXu85efAEnaZLqWLBt+xBu+ZOe3ZZZroJCU0BUvCBTnc90iE2m6H0jqyr2bccMoneovLx1k8W3jjnV2E00gHAcOs4n7U5REqsE+0ZKCkBvH9F5SHZ1ZIbnK5+sa6uM4ldslulhTE3Xi/64z2pc37WxdrHViieKdYfUa27/8uYLuanamEV41Z60clZShSZIOOoc8c2fsDGuUduA98bVXgJjm8zDovpWjYWT7/4lAVg2Q+WH2qpJqPbrUC0sQ7RcEA2umNN27thT9/18ImzNf2a1SsxFVABwfPk8KEObAT0I41tFJI4TuIb1KaUzH4fCNvRqIbyQTUoC+OhR7XQVXU2e0FV2QA9j8QDNXzT8Wxv5sgVnv5UcQcSI6bIqiap+gez4WTkODIHAsopFgxyUM8SJ7/zGtdQAXXN5s/V9pImiamugUmxQPmLORMWpJ9AjMv/nUResePQJzVw9TW9+pMbxJcLg6RcLFZFmYGbZiC/xQ+G1oVM+wp3PHoqUyJa/94yzOo2kFGAnbtCNX9Xl18w=
