baseURL = "https://warnersports.org/"
languageCode = "en-us"
title = "WYSA"
theme = "ananke"


[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Registration"
    identifier = "registration"
    url = "/registration/"

[[menu.main]]
    name = "Links"
    identifier = "warner-area"
    url = "/warner-area/"